language: php

php:
  - 7.1

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testing;'
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate


script:
  - ./vendor/bin/phpunit

cache:
  directories:
    - vendor

services:
  - mysql
